use_default_settings: true

general:
  instance_name: "GlezAI-Crawler"

server:
  secret_key: "glezai24-secret-key-render-12345"
  limiter: false       # Desactiva el bloqueo de IPs/Bots
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json             # Habilita las respuestas en JSON para el backend

engines:
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: google
    engine: google
    disabled: false
